image:
  file: .gitpod.Dockerfile

tasks:
  - name: Update and setup
    init: |
      git config --global user.name "YOUR_NAME"
      git config --global user.email "YOUR_EMAIL"
      echo "Ambiente Gitpod pronto!"
    command: |
      cd frontend
      flutter --version
      cd ../backend
      node --version
      echo "Frontend e backend pronti in cloud!"
ports:
  - port: 8080
    onOpen: open-preview
  - port: 3000
    onOpen: open-preview
vscode:
  extensions:
    - dart-code.flutter
    - ms-vscode.vscode-node-azure-pack
